---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelter
  labels:
    app: shelter
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shelter
  labels:
    app: shelter
# NOTE: number values needs to be quoted
data:
  SHELTER_DB: /data/shelter/db.pickle
  SHELTER_CIDR_ALLOW: "10.42.0.0/16"
  SHELTER_SLEEP_MAX_SECONDS: "10"
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: shelter
  labels:
    app: shelter
spec:
  rules:
    - host: shelter.trestle.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shelter
                port:
                  name: http
---
apiVersion: v1
kind: Service
metadata:
  name: shelter
  labels:
    app: shelter
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.122.140
  selector:
    app: shelter
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelter
  labels:
    app: shelter
spec:
  selector:
    matchLabels:
      app: shelter
  replicas: 2
  template:
    metadata:
      labels:
        app: shelter
    spec:
      volumes:
        - name: shelter
          persistentVolumeClaim:
            claimName: shelter
      containers:
        - name: shelter
          image: ghcr.io/jostho/shelter:fcdec64
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: SHELTER_DB
              valueFrom:
                configMapKeyRef:
                  name: shelter
                  key: SHELTER_DB
            - name: SHELTER_CIDR_ALLOW
              valueFrom:
                configMapKeyRef:
                  name: shelter
                  key: SHELTER_CIDR_ALLOW
            - name: SHELTER_SLEEP_MAX_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: shelter
                  key: SHELTER_SLEEP_MAX_SECONDS
          ports:
            - containerPort: 5000
              name: http
          volumeMounts:
            - mountPath: /data/shelter
              name: shelter
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
      nodeSelector:
        trestle-role: worker
