---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysaas
data:
  MYSQL_ROOT_HOST: '%'  # allow access from outside localhost
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app: mysaas
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: 'cjAwdHBhNTU='
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysaas
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.122.146
  selector:
    app: mysaas
  ports:
    - name: mysql
      port: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysaas
spec:
  selector:
    matchLabels:
      app: mysaas
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysaas
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.26
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_ROOT_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql
                  key: MYSQL_ROOT_HOST
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-pv
  volumeClaimTemplates:
    - metadata:
        name: mysql-pv
        labels:
          app: mysaas
      spec:
        storageClassName: nfs-client
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 400Mi
