---
name: CI

# yamllint disable-line
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint .
      - name: Run kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:v0.6.6
        with:
          entrypoint: /kubeconform
          args: "-kubernetes-version 1.29.5 -summary -ignore-missing-schemas -ignore-filename-pattern .github ."
