---
name: Manual

# yamllint disable-line
on:
  workflow_dispatch:
    inputs:
      repo:
        description: Repository
        required: true

jobs:
  update-image::

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update image in yaml
        run: |
          REPO="${{ github.event.inputs.name }}"
          API_URL="https://api.github.com/repos/jostho/$REPO/commits/master"
          GIT_SHA=$(curl -sS -H "Accept: application/vnd.github.VERSION.sha" $API_URL)
          SHORT_SHA="${GIT_SHA::7}"
          for yaml in $REPO/app-$REPO.yaml $REPO-static/app-$REPO-static.yaml
          do
            if [ -f $yaml ]
            then
              sed -i "/image: ghcr.io/ s/.......$/$SHORT_SHA/" $yaml
              git add $yaml
            fi
          done
          git status -s
          git config user.name "Jose Thomas"
          git config user.email "jostho@users.noreply.github.com"
          git commit -m "Use the latest image"
          git show
